export { default as HomePage } from './HomePage'
export { default as AboutUsPage } from './AboutUsPage'
export { default as ProfilePage } from './ProfilePage'
export { default as RecipesPage } from './RecipesPage'
export { default as SingleRecipe } from './SingleRecipe'
export {default as LoginPage} from './LoginPage'
export {default as RegisterPage} from './RegisterPage'